<?php namespace Tests\Integration\Commands;

/**
 * TableExport Command Integration Tests
 *
 * Tests the table:export command which exports table data to SQL or CSV
 * directly without requiring model classes.
 *
 * Test Coverage:
 *   - Exporting to SQL format
 *   - Exporting to CSV format
 *   - Auto-generated filenames with timestamps
 *   - Custom filenames
 *   - Attempting to export non-existent table
 *   - Required argument validation
 *   - Overwrite confirmation
 *
 * @category Tests
 * @package  Tests\Integration\Commands
 */

use Tests\RolineTest;

class TableExportTest extends RolineTest
{
    /**
     * Test exporting table to SQL format
     *
     * @return void
     */
    public function testExportToSQLFormat()
    {
        $tableName = 'export_sql_test';
        $exportFile = RACHIE_ROOT . '/application/storage/exports/table_export.sql';

        $this->trackTable($tableName);
        $this->trackFile($exportFile);

        // Create table with data using raw SQL
        $db = $this->getDb();
        $db->exec("CREATE TABLE `{$tableName}` (
            id INT PRIMARY KEY AUTO_INCREMENT,
            name VARCHAR(100) NOT NULL
        )");
        $this->assertTableExists($tableName);

        // Insert test data
        $this->insertTestData($tableName, [
            ['name' => 'Test Entry'],
        ]);

        // Export to SQL
        $result = $this->runCommand("table:export {$tableName} table_export.sql");

        // Export file should exist
        $this->assertFileExists($exportFile, "Export file should be created");

        // File should contain SQL INSERT statements
        $content = file_get_contents($exportFile);
        $this->assertStringContainsString('INSERT INTO', $content,
            "Export should contain INSERT statements");
        $this->assertStringContainsString($tableName, $content,
            "Export should reference table name");

        // Output should confirm success
        $output = strtolower($result['output']);
        $this->assertTrue(
            str_contains($output, 'complete') || str_contains($output, 'success'),
            "Expected success message in output: {$result['output']}"
        );
    }

    /**
     * Test exporting table to CSV format
     *
     * @return void
     */
    public function testExportToCSVFormat()
    {
        $tableName = 'export_csv_test';
        $exportFile = RACHIE_ROOT . '/application/storage/exports/table_export.csv';

        $this->trackTable($tableName);
        $this->trackFile($exportFile);

        // Create table with data using raw SQL
        $db = $this->getDb();
        $db->exec("CREATE TABLE `{$tableName}` (
            id INT PRIMARY KEY AUTO_INCREMENT,
            title VARCHAR(100) NOT NULL
        )");
        $this->assertTableExists($tableName);

        // Insert test data
        $this->insertTestData($tableName, [
            ['title' => 'CSV Test'],
        ]);

        // Export to CSV
        $result = $this->runCommand("table:export {$tableName} table_export.csv");

        // Export file should exist
        $this->assertFileExists($exportFile, "Export file should be created");

        // File should contain CSV data
        $content = file_get_contents($exportFile);
        $this->assertStringContainsString('id', $content,
            "CSV should contain column headers");
        $this->assertStringContainsString('title', $content,
            "CSV should contain column names");
    }

    /**
     * Test auto-generated filename with timestamp
     *
     * @return void
     */
    public function testAutoGeneratedFilename()
    {
        $tableName = 'auto_export';
        $exportDir = RACHIE_ROOT . '/application/storage/exports';

        $this->trackTable($tableName);

        // Create table using raw SQL
        $db = $this->getDb();
        $db->exec("CREATE TABLE `{$tableName}` (id INT PRIMARY KEY)");
        $this->assertTableExists($tableName);

        // Export without filename (should auto-generate)
        $result = $this->runCommand("table:export {$tableName}");

        // Find generated file
        $files = glob($exportDir . '/' . $tableName . '_*.sql');
        $this->assertNotEmpty($files, "Auto-generated export file should exist");

        // Track for cleanup
        if (!empty($files)) {
            $this->trackFile($files[0]);
        }

        // Filename should contain timestamp pattern
        $output = $result['output'];
        $this->assertMatchesRegularExpression(
            '/\d{4}-\d{2}-\d{2}_\d{6}/',
            $output,
            "Filename should contain timestamp: {$output}"
        );
    }

    /**
     * Test exporting non-existent table
     *
     * @return void
     */
    public function testExportNonExistentTable()
    {
        $tableName = 'no_such_table';

        $result = $this->runCommand("table:export {$tableName}");

        $output = strtolower($result['output']);
        $this->assertTrue(
            str_contains($output, 'does not exist') || str_contains($output, 'not found'),
            "Expected error about non-existent table: {$result['output']}"
        );
    }

    /**
     * Test table:export requires table name argument
     *
     * @return void
     */
    public function testRequiresTableNameArgument()
    {
        $result = $this->runCommand("table:export");

        $output = strtolower($result['output']);
        $this->assertTrue(
            str_contains($output, 'required') || str_contains($output, 'usage'),
            "Expected error about missing argument: {$result['output']}"
        );
    }

    /**
     * Test overwrite confirmation
     *
     * @return void
     */
    public function testOverwriteConfirmation()
    {
        $tableName = 'overwrite_export';
        $exportFile = RACHIE_ROOT . '/application/storage/exports/overwrite.sql';

        $this->trackTable($tableName);
        $this->trackFile($exportFile);

        // Create table using raw SQL
        $db = $this->getDb();
        $db->exec("CREATE TABLE `{$tableName}` (id INT PRIMARY KEY)");
        $this->assertTableExists($tableName);

        // Create initial export
        $this->runCommand("table:export {$tableName} overwrite.sql");
        $this->assertFileExists($exportFile);

        // Try to export again with 'no' (cancel overwrite)
        $result = $this->runCommand("table:export {$tableName} overwrite.sql", ['no']);

        // Should be cancelled
        $output = strtolower($result['output']);
        $this->assertTrue(
            str_contains($output, 'cancelled') || str_contains($output, 'cancel'),
            "Expected cancellation message: {$result['output']}"
        );
    }
}
